jobs:

######################
###### Linux #########
######################

- job: Linux
  timeoutInMinutes: 120
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      x86_64:
        dockerImage: 'x86_64'
        dockerName: 'Debian Stretch (x86_64)'
        platform: 'x11'
      ARMv6hf (Raspberry Pi v1 & ZERO):
        dockerImage: 'armv6l'
        dockerName: 'Debian Stretch (Raspberry Pi v1 & ZERO)'
        platform: 'rpi'
      ARMv7hf (Raspberry Pi 2 & 3):
        dockerImage: 'armv7l'
        dockerName: 'Debian Stretch (Raspberry Pi 2 & 3)'
        platform: 'rpi'
      ARMv8 (Generic AARCH64):
        dockerImage: 'aarch64'
        dockerName: 'ARMv8 (Generic AARCH64)'
        platform: 'amlogic'

  steps:
  - checkout: self # represents the repo where the initial Pipelines YAML file was found
    submodules: recursive # set to 'recursive' to get submodules of submodules

  # build process
  - bash: ./.ci/ci_build.sh
    displayName: 'Build $(dockerName) packages'
    env:
      DOCKER_IMAGE: $(dockerImage)
      DOCKER_TAG: stretch
      DOCKER_NAME: $(dockerName)
      PLATFORM: $(platform)

######################
###### macOS #########
######################

- job: macOS
  timeoutInMinutes: 120
  pool:
    vmImage: 'macOS-10.14'

  steps:
  - checkout: self # represents the repo where the initial Pipelines YAML file was found
    submodules: recursive # set to 'recursive' to get submodules of submodules

  # install dependencies
  - bash: ./.ci/ci_install.sh
    displayName: 'Install dependencies'

  # build process
  - bash: ./.ci/ci_build.sh
    env:
      PLATFORM: 'osx'
    condition: succeeded()
    displayName: 'Build macOS 10.13 packages'

######################
###### windows #######
######################

- job: windows
  timeoutInMinutes: 120
  pool:
    vmImage: 'windows-latest'
  variables:
    VCINSTALLDIR: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC'

  steps:
  - checkout: self # represents the repo where the initial Pipelines YAML file was found
    submodules: recursive # set to 'recursive' to get submodules of submodules

  # install qt 5.15 via aqtinstall
  - script: |
      cd $(Build.SourcesDirectory)
      python -m pip install aqtinstall
      python -m aqt install -O c:\Qt 5.15.0 windows desktop win64_msvc2019_64
    displayName: 'Install Qt'

  # use Python 3.x from the tool cache
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
      architecture: 'x64'
    displayName: 'Install Python'

  # install nsis via chocolatey
  - powershell: choco install --no-progress nsis -y
    displayName: 'Install NSIS'

  # install openssl via chocolatey
  - powershell: choco install --no-progress openssl -y
    displayName: 'Install OpenSSL'

  # register x64 architecture environment
  - script: |
      call "%VCINSTALLDIR%\Auxiliary\Build\vcvars64.bat"
    displayName: 'Set up x64 build architecture environment'

  # build process
  - bash: ./.ci/ci_build.sh
    env:
      PLATFORM: 'windows'
    condition: succeeded()
    displayName: 'Build windows packages'
