extraction:
  cpp:
    prepare:
      packages:
      - "git"
      - "cmake"
      - "build-essential"
      - "qtbase5-dev"
      - "libqt5serialport5-dev"
      - "libqt5sql5-sqlite"
      - "libqt5svg5-dev"
      - "libqt5x11extras5-dev"
      - "libusb-1.0-0-dev"
      - "python3-dev"
      - "libcec-dev"
      - "libxcb-image0-dev"
      - "libxcb-util0-dev"
      - "libxcb-shm0-dev"
      - "libxcb-render0-dev"
      - "libxcb-randr0-dev"
      - "libxrandr-dev"
      - "libxrender-dev"
      - "libavahi-core-dev"
      - "libavahi-compat-libdnssd-dev"
      - "libturbojpeg0-dev"
      - "libjpeg-dev"
      - "libssl-dev"
