name: Download Pre-Built Dependencies
description: Download Pre-Built Dependencies for Hyperion to speed-up the CI build
inputs:
  os:
    type: string
    description: Operating System
    required: true
  architecture:
    type: string
    description: Linux architecture
    required: false
    default: 'amd64'
  build_type:
    type: string
    description: Build type
    required: false
    default: 'release'
outputs:
  cmakeArgs:
    description: "Resulting CMake arguments"
    value: ${{ steps.download-pre-built-deps.outputs.cmake-args }}
  qtVersion:
    description: "Determined Qt version"
    value: ${{ steps.download-pre-built-deps.outputs.qt-version }}
runs:
  using: composite
  steps:
    - name: Download Deps
      id: download-pre-built-deps
      working-directory: ${{ github.action_path }}
      shell: bash
      run: |
        preBuiltDeps='buildspec.json'
        baseURL=$(jq -r '.baseUrl' $preBuiltDeps)
        version=$(jq -r '.version' $preBuiltDeps)
        downloadHash=$(jq -r '.hashes .${{ inputs.os }} .${{ inputs.architecture }} .${{ inputs.build_type }}' $preBuiltDeps)
        qtVersion=$(jq -r '.hashes .${{ inputs.os }} .${{ inputs.architecture }} .qt_version' $preBuiltDeps)
        downloadFilename=${{ inputs.os }}-${{ inputs.architecture }}-qt$qtVersion-${{ inputs.build_type }}-$version.tar.gz
        echo 💾 Download "$downloadFilename"...
        curl -OL "$baseURL"/"$version"/"$downloadFilename"
        if [[ ${{ inputs.os }} == 'windows' ]]; then
          computedHash=$(powershell -Command "(Get-FileHash -Path \"$downloadFilename\" -Algorithm SHA256).Hash.ToLower()")
          destDir=C:/tmp
        else
          computedHash=$(sha256sum "$downloadFilename" | awk '{print $1}')
          destDir=/tmp/deps
        fi
        echo 👀 Check Hash...
        if [[ "$computedHash" == "$downloadHash" ]]; then
          mkdir "$destDir"
          tar -xzf "$downloadFilename" -C "$destDir"
          if [[ ${{ inputs.os }} != 'windows' ]]; then
            chmod +x "$destDir"/bin/*
          fi
          echo ✅ Hash check passed.
          echo "cmake-args="-DUSE_PRE_BUILT_DEPS=ON -DPRE_BUILT_DEPS_DIR=$destDir"" >> $GITHUB_OUTPUT
          echo "qt-version=$qtVersion" >> $GITHUB_OUTPUT
        else
          echo ❌ Hash check failed.
          echo "cmake-args=" >> $GITHUB_OUTPUT
          echo "qt-version=" >> $GITHUB_OUTPUT
        fi
