#!/bin/sh

echo "---Hyperion ambient light prerm ---"

# search for users in system, returns first entry
FOUND_USR=`who | grep -o '^\w*\b'` || "root"

# stop running daemon before we delete it
HYPERION_RUNNING=false
pgrep hyperiond > /dev/null 2>&1 && HYPERION_RUNNING=true

if grep -m1 systemd /proc/1/comm > /dev/null
then
	echo "---> stop init deamon: systemd"
	# systemd
	$HYPERION_RUNNING && systemctl stop hyperiond"@${FOUND_USR}" 2> /dev/null
	# disable user specific symlink
	echo "---> Disable service and remove entry"
	systemctl -q disable hyperiond"@${FOUND_USR}"
	rm -v /etc/systemd/system/hyperiond@.service 2>/dev/null

elif [ -e /sbin/initctl ]
then
	echo "---> stop init deamon: upstart"
	# upstart
	$HYPERION_RUNNING && initctl stop hyperiond
	echo "---> Remove upstart service"
	rm -v /etc/init/hyperion* 2>/dev/null
	initctl reload-configuration

else
	echo "---> stop init deamon: sysV"
	# sysV
	$HYPERION_RUNNING && service hyperiond stop 2>/dev/null
	echo "---> Remove sysV service"
	update-rc.d -f hyperion remove
	rm /etc/init.d/hyperion* 2>/dev/null
fi

# In case we don't use a service kill all instances
killall hyperiond 2> /dev/null

# delete desktop icons; desktop-file-edit is a workaround to hide the entry and delete it afterwards manual.
# TODO Better way for deletion and keep the desktop in sync without logout/login or desktop dependend cmds?
echo "---> Delete Hyperion desktop icons"
desktop-file-edit --set-key=NoDisplay --set-value=true /usr/share/applications/hyperiond.desktop 2>/dev/null
rm -v /usr/share/applications/hyperion* 2>/dev/null
rm -rv /usr/share/pixmaps/hyperion 2>/dev/null

exit 0
