find_package(PkgConfig)

if (PkgConfig_FOUND)
	pkg_check_modules(PC_LIBFTDI1 QUIET libftdi1)
endif()

if (PC_LIBFTDI1_FOUND)
	add_library(libftdi INTERFACE IMPORTED GLOBAL)
	set_target_properties(libftdi PROPERTIES
		INTERFACE_LINK_LIBRARIES "${PC_LIBFTDI1_LDFLAGS}"
		INTERFACE_COMPILE_OPTIONS "${PC_LIBFTDI1_CFLAGS}")

	set(LIBFTDI1_INCLUDE_DIRS "${PC_LIBFTDI1_INCLUDE_DIRS}")
	set(LIBFTDI1_LIBRARIES "${PC_LIBFTDI1_LIBRARIES}")
	set(LIBFTDI1_VERSION_STRING "${PC_LIBFTDI1_VERSION}")
endif()

if (NOT TARGET libftdi)
	find_path(LIBFTDI1_INCLUDE_DIRS ftdi.h PATH_SUFFIXES libftdi1)
	find_library(LIBFTDI1_LIBRARIES ftdi1)

	add_library(libftdi INTERFACE IMPORTED GLOBAL)
	set_target_properties(libftdi PROPERTIES
		INTERFACE_INCLUDE_DIRECTORIES "${LIBFTDI1_INCLUDE_DIRS}"
		INTERFACE_LINK_LIBRARIES "${LIBFTDI1_LIBRARIES}"
	)
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(LibFTDI1
	REQUIRED_VARS LIBFTDI1_LIBRARIES
)

mark_as_advanced(LIBFTDI1_INCLUDE_DIRS LIBFTDI1_LIBRARIES)
