function(SetVersionNumber PREFIX VERSION_MAJOR VERSION_MINOR VERSION_PATCH VERSION_PRE)
  set(${PREFIX}_VERSION_MAJOR ${VERSION_MAJOR} PARENT_SCOPE)
  set(${PREFIX}_VERSION_MINOR ${VERSION_MINOR} PARENT_SCOPE)
  set(${PREFIX}_VERSION_PATCH ${VERSION_PATCH} PARENT_SCOPE)
  if(NOT VERSION_PRE MATCHES "stable")
    set(${PREFIX}_VERSION_PRE   ${VERSION_PRE}   PARENT_SCOPE)
    set( VERSION_PRE_FULL "-${VERSION_PRE}")
  endif()
  set(${PREFIX}_VERSION
        "${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}${VERSION_PRE_FULL}"
        PARENT_SCOPE)
endfunction()