name: Hyperion CI/PR Builds
run-name: |
  ${{ github.event_name == 'push' && '🌱 Push build -' || '' }}
  ${{ github.event_name == 'pull_request' && format('📦 Artifacts build for PR {0} - {1}', github.event.pull_request.number, github.event.pull_request.title) || github.event.head_commit.message }}

on:
  push:
    branches:
      - '**'
    tags:
      - '*'
  pull_request:
    branches:
      - 'master'

jobs:

  # Build Windows Artifacts
  windows:
    name: 🪟 Windows
    uses: ./.github/workflows/windows.yml
    secrets: inherit
    with:
      event_name: ${{ github.event_name }}
      pull_request_number: ${{ github.event.pull_request.number }}
      publish: ${{ startsWith(github.event.ref, 'refs/tags') }}
